public interface testint{
    void im1();

}
/*
Debug window

public class test extends testabs implements testint, testint2 {
    public override void m1(){
    system.debug('I am in m1');
    }
    
    public void im1(){
    system.debug('I am in im1');
    }
    
    public void im2(){
    system.debug('I am in im2');
    }
}
    test obj = new test();
    obj.m1();
obj.m2();
obj.im1();
obj.im2();
   
*/